idf_component_register(
    SRCS            "cores/esp32/delay.c"
                    "cores/esp32/itoa.c"
                    "cores/esp32/WInterrupts.c"
                    "cores/esp32/wiring_analog.c"
                    "cores/esp32/wiring.c"
                    "cores/esp32/wiring_digital.c"
                    "cores/esp32/IPAddress.cpp"
                    "cores/esp32/main.cpp"
                    "cores/esp32/Print.cpp"
                    "cores/esp32/Stream.cpp"
                    "cores/esp32/WMath.cpp"
                    "cores/esp32/WString.cpp"

                    "libraries/ArduinoECCX08/"
                    "libraries/SPIS/"
                    "libraries/WiFi/"
                    "libraries/Wire/"

                    "libraries/ArduinoBearSSL/src/aiotc_profile.c"
                    "libraries/ArduinoBearSSL/src/ArduinoBearSSL.cpp"
                    "libraries/ArduinoBearSSL/src/bearssl"
                    "libraries/ArduinoBearSSL/src/BearSSLClient.cpp"
                    "libraries/ArduinoBearSSL/src/SHA1.cpp"
                    "libraries/ArduinoBearSSL/src/SHA256.cpp"
                    "libraries/ArduinoBearSSL/src/SHA.cpp"
                    "libraries/ArduinoBearSSL/src/utility"


                    "libraries/ArduinoBearSSL/src/bearssl/aes_big_cbcdec.c"
                    "libraries/ArduinoBearSSL/src/bearssl/aes_big_cbcenc.c"
                    "libraries/ArduinoBearSSL/src/bearssl/aes_big_ctr.c"
                    "libraries/ArduinoBearSSL/src/bearssl/aes_big_ctrcbc.c"
                    "libraries/ArduinoBearSSL/src/bearssl/aes_big_dec.c"
                    "libraries/ArduinoBearSSL/src/bearssl/aes_big_enc.c"
                    "libraries/ArduinoBearSSL/src/bearssl/aes_common.c"
                    "libraries/ArduinoBearSSL/src/bearssl/aes_ct64.c"
                    "libraries/ArduinoBearSSL/src/bearssl/aes_ct64_cbcdec.c"
                    "libraries/ArduinoBearSSL/src/bearssl/aes_ct64_cbcenc.c"
                    "libraries/ArduinoBearSSL/src/bearssl/aes_ct64_ctr.c"
                    "libraries/ArduinoBearSSL/src/bearssl/aes_ct64_ctrcbc.c"
                    "libraries/ArduinoBearSSL/src/bearssl/aes_ct64_dec.c"
                    "libraries/ArduinoBearSSL/src/bearssl/aes_ct64_enc.c"
                    "libraries/ArduinoBearSSL/src/bearssl/aes_ct.c"
                    "libraries/ArduinoBearSSL/src/bearssl/aes_ct_cbcdec.c"
                    "libraries/ArduinoBearSSL/src/bearssl/aes_ct_cbcenc.c"
                    "libraries/ArduinoBearSSL/src/bearssl/aes_ct_ctr.c"
                    "libraries/ArduinoBearSSL/src/bearssl/aes_ct_ctrcbc.c"
                    "libraries/ArduinoBearSSL/src/bearssl/aes_ct_dec.c"
                    "libraries/ArduinoBearSSL/src/bearssl/aes_ct_enc.c"
                    "libraries/ArduinoBearSSL/src/bearssl/aesctr_drbg.c"
                    "libraries/ArduinoBearSSL/src/bearssl/aes_pwr8.c"
                    "libraries/ArduinoBearSSL/src/bearssl/aes_pwr8_cbcdec.c"
                    "libraries/ArduinoBearSSL/src/bearssl/aes_pwr8_cbcenc.c"
                    "libraries/ArduinoBearSSL/src/bearssl/aes_pwr8_ctr.c"
                    "libraries/ArduinoBearSSL/src/bearssl/aes_pwr8_ctrcbc.c"
                    "libraries/ArduinoBearSSL/src/bearssl/aes_small_cbcdec.c"
                    "libraries/ArduinoBearSSL/src/bearssl/aes_small_cbcenc.c"
                    "libraries/ArduinoBearSSL/src/bearssl/aes_small_ctr.c"
                    "libraries/ArduinoBearSSL/src/bearssl/aes_small_ctrcbc.c"
                    "libraries/ArduinoBearSSL/src/bearssl/aes_small_dec.c"
                    "libraries/ArduinoBearSSL/src/bearssl/aes_small_enc.c"
                    "libraries/ArduinoBearSSL/src/bearssl/aes_x86ni.c"
                    "libraries/ArduinoBearSSL/src/bearssl/aes_x86ni_cbcdec.c"
                    "libraries/ArduinoBearSSL/src/bearssl/aes_x86ni_cbcenc.c"
                    "libraries/ArduinoBearSSL/src/bearssl/aes_x86ni_ctr.c"
                    "libraries/ArduinoBearSSL/src/bearssl/asn1enc.c"
                    "libraries/ArduinoBearSSL/src/bearssl/ccm.c"
                    "libraries/ArduinoBearSSL/src/bearssl/ccopy.c"
                    "libraries/ArduinoBearSSL/src/bearssl/chacha20_ct.c"
                    "libraries/ArduinoBearSSL/src/bearssl/chacha20_sse2.c"
                    "libraries/ArduinoBearSSL/src/bearssl/dec16be.c"
                    "libraries/ArduinoBearSSL/src/bearssl/dec16le.c"
                    "libraries/ArduinoBearSSL/src/bearssl/dec32be.c"
                    "libraries/ArduinoBearSSL/src/bearssl/dec32le.c"
                    "libraries/ArduinoBearSSL/src/bearssl/dec64be.c"
                    "libraries/ArduinoBearSSL/src/bearssl/dec64le.c"
                    "libraries/ArduinoBearSSL/src/bearssl/des_ct.c"
                    "libraries/ArduinoBearSSL/src/bearssl/des_ct_cbcdec.c"
                    "libraries/ArduinoBearSSL/src/bearssl/des_ct_cbcenc.c"
                    "libraries/ArduinoBearSSL/src/bearssl/des_support.c"
                    "libraries/ArduinoBearSSL/src/bearssl/des_tab.c"
                    "libraries/ArduinoBearSSL/src/bearssl/des_tab_cbcdec.c"
                    "libraries/ArduinoBearSSL/src/bearssl/des_tab_cbcenc.c"
                    "libraries/ArduinoBearSSL/src/bearssl/dig_oid.c"
                    "libraries/ArduinoBearSSL/src/bearssl/dig_size.c"
                    "libraries/ArduinoBearSSL/src/bearssl/eax.c"
                    "libraries/ArduinoBearSSL/src/bearssl/ec_all_m15.c"
                    "libraries/ArduinoBearSSL/src/bearssl/ec_all_m31.c"
                    "libraries/ArduinoBearSSL/src/bearssl/ec_c25519_i15.c"
                    "libraries/ArduinoBearSSL/src/bearssl/ec_c25519_i31.c"
                    "libraries/ArduinoBearSSL/src/bearssl/ec_c25519_m15.c"
                    "libraries/ArduinoBearSSL/src/bearssl/ec_c25519_m31.c"
                    "libraries/ArduinoBearSSL/src/bearssl/ec_curve25519.c"
                    "libraries/ArduinoBearSSL/src/bearssl/ec_default.c"
                    "libraries/ArduinoBearSSL/src/bearssl/ecdsa_atr.c"
                    "libraries/ArduinoBearSSL/src/bearssl/ecdsa_default_sign_asn1.c"
                    "libraries/ArduinoBearSSL/src/bearssl/ecdsa_default_sign_raw.c"
                    "libraries/ArduinoBearSSL/src/bearssl/ecdsa_default_vrfy_asn1.c"
                    "libraries/ArduinoBearSSL/src/bearssl/ecdsa_default_vrfy_raw.c"
                    "libraries/ArduinoBearSSL/src/bearssl/ecdsa_i15_bits.c"
                    "libraries/ArduinoBearSSL/src/bearssl/ecdsa_i15_sign_asn1.c"
                    "libraries/ArduinoBearSSL/src/bearssl/ecdsa_i15_sign_raw.c"
                    "libraries/ArduinoBearSSL/src/bearssl/ecdsa_i15_vrfy_asn1.c"
                    "libraries/ArduinoBearSSL/src/bearssl/ecdsa_i15_vrfy_raw.c"
                    "libraries/ArduinoBearSSL/src/bearssl/ecdsa_i31_bits.c"
                    "libraries/ArduinoBearSSL/src/bearssl/ecdsa_i31_sign_asn1.c"
                    "libraries/ArduinoBearSSL/src/bearssl/ecdsa_i31_sign_raw.c"
                    "libraries/ArduinoBearSSL/src/bearssl/ecdsa_i31_vrfy_asn1.c"
                    "libraries/ArduinoBearSSL/src/bearssl/ecdsa_i31_vrfy_raw.c"
                    "libraries/ArduinoBearSSL/src/bearssl/ecdsa_rta.c"
                    "libraries/ArduinoBearSSL/src/bearssl/ec_keygen.c"
                    "libraries/ArduinoBearSSL/src/bearssl/ec_p256_m15.c"
                    "libraries/ArduinoBearSSL/src/bearssl/ec_p256_m31.c"
                    "libraries/ArduinoBearSSL/src/bearssl/ec_prime_i15.c"
                    "libraries/ArduinoBearSSL/src/bearssl/ec_prime_i31.c"
                    "libraries/ArduinoBearSSL/src/bearssl/ec_pubkey.c"
                    "libraries/ArduinoBearSSL/src/bearssl/ec_secp256r1.c"
                    "libraries/ArduinoBearSSL/src/bearssl/ec_secp384r1.c"
                    "libraries/ArduinoBearSSL/src/bearssl/ec_secp521r1.c"
                    "libraries/ArduinoBearSSL/src/bearssl/enc16be.c"
                    "libraries/ArduinoBearSSL/src/bearssl/enc16le.c"
                    "libraries/ArduinoBearSSL/src/bearssl/enc32be.c"
                    "libraries/ArduinoBearSSL/src/bearssl/enc32le.c"
                    "libraries/ArduinoBearSSL/src/bearssl/enc64be.c"
                    "libraries/ArduinoBearSSL/src/bearssl/enc64le.c"
                    "libraries/ArduinoBearSSL/src/bearssl/encode_ec_pk8der.c"
                    "libraries/ArduinoBearSSL/src/bearssl/encode_ec_rawder.c"
                    "libraries/ArduinoBearSSL/src/bearssl/encode_rsa_pk8der.c"
                    "libraries/ArduinoBearSSL/src/bearssl/encode_rsa_rawder.c"
                    "libraries/ArduinoBearSSL/src/bearssl/gcm.c"
                    "libraries/ArduinoBearSSL/src/bearssl/ghash_ctmul32.c"
                    "libraries/ArduinoBearSSL/src/bearssl/ghash_ctmul64.c"
                    "libraries/ArduinoBearSSL/src/bearssl/ghash_ctmul.c"
                    "libraries/ArduinoBearSSL/src/bearssl/ghash_pclmul.c"
                    "libraries/ArduinoBearSSL/src/bearssl/ghash_pwr8.c"
                    "libraries/ArduinoBearSSL/src/bearssl/hkdf.c"
                    "libraries/ArduinoBearSSL/src/bearssl/hmac.c"
                    "libraries/ArduinoBearSSL/src/bearssl/hmac_ct.c"
                    "libraries/ArduinoBearSSL/src/bearssl/hmac_drbg.c"
                    "libraries/ArduinoBearSSL/src/bearssl/i15_add.c"
                    "libraries/ArduinoBearSSL/src/bearssl/i15_bitlen.c"
                    "libraries/ArduinoBearSSL/src/bearssl/i15_decmod.c"
                    "libraries/ArduinoBearSSL/src/bearssl/i15_decode.c"
                    "libraries/ArduinoBearSSL/src/bearssl/i15_decred.c"
                    "libraries/ArduinoBearSSL/src/bearssl/i15_encode.c"
                    "libraries/ArduinoBearSSL/src/bearssl/i15_fmont.c"
                    "libraries/ArduinoBearSSL/src/bearssl/i15_iszero.c"
                    "libraries/ArduinoBearSSL/src/bearssl/i15_moddiv.c"
                    "libraries/ArduinoBearSSL/src/bearssl/i15_modpow2.c"
                    "libraries/ArduinoBearSSL/src/bearssl/i15_modpow.c"
                    "libraries/ArduinoBearSSL/src/bearssl/i15_montmul.c"
                    "libraries/ArduinoBearSSL/src/bearssl/i15_mulacc.c"
                    "libraries/ArduinoBearSSL/src/bearssl/i15_muladd.c"
                    "libraries/ArduinoBearSSL/src/bearssl/i15_ninv15.c"
                    "libraries/ArduinoBearSSL/src/bearssl/i15_reduce.c"
                    "libraries/ArduinoBearSSL/src/bearssl/i15_rshift.c"
                    "libraries/ArduinoBearSSL/src/bearssl/i15_sub.c"
                    "libraries/ArduinoBearSSL/src/bearssl/i15_tmont.c"
                    "libraries/ArduinoBearSSL/src/bearssl/i31_add.c"
                    "libraries/ArduinoBearSSL/src/bearssl/i31_bitlen.c"
                    "libraries/ArduinoBearSSL/src/bearssl/i31_decmod.c"
                    "libraries/ArduinoBearSSL/src/bearssl/i31_decode.c"
                    "libraries/ArduinoBearSSL/src/bearssl/i31_decred.c"
                    "libraries/ArduinoBearSSL/src/bearssl/i31_encode.c"
                    "libraries/ArduinoBearSSL/src/bearssl/i31_fmont.c"
                    "libraries/ArduinoBearSSL/src/bearssl/i31_iszero.c"
                    "libraries/ArduinoBearSSL/src/bearssl/i31_moddiv.c"
                    "libraries/ArduinoBearSSL/src/bearssl/i31_modpow2.c"
                    "libraries/ArduinoBearSSL/src/bearssl/i31_modpow.c"
                    "libraries/ArduinoBearSSL/src/bearssl/i31_montmul.c"
                    "libraries/ArduinoBearSSL/src/bearssl/i31_mulacc.c"
                    "libraries/ArduinoBearSSL/src/bearssl/i31_muladd.c"
                    "libraries/ArduinoBearSSL/src/bearssl/i31_ninv31.c"
                    "libraries/ArduinoBearSSL/src/bearssl/i31_reduce.c"
                    "libraries/ArduinoBearSSL/src/bearssl/i31_rshift.c"
                    "libraries/ArduinoBearSSL/src/bearssl/i31_sub.c"
                    "libraries/ArduinoBearSSL/src/bearssl/i31_tmont.c"
                    "libraries/ArduinoBearSSL/src/bearssl/i32_add.c"
                    "libraries/ArduinoBearSSL/src/bearssl/i32_bitlen.c"
                    "libraries/ArduinoBearSSL/src/bearssl/i32_decmod.c"
                    "libraries/ArduinoBearSSL/src/bearssl/i32_decode.c"
                    "libraries/ArduinoBearSSL/src/bearssl/i32_decred.c"
                    "libraries/ArduinoBearSSL/src/bearssl/i32_div32.c"
                    "libraries/ArduinoBearSSL/src/bearssl/i32_encode.c"
                    "libraries/ArduinoBearSSL/src/bearssl/i32_fmont.c"
                    "libraries/ArduinoBearSSL/src/bearssl/i32_iszero.c"
                    "libraries/ArduinoBearSSL/src/bearssl/i32_modpow.c"
                    "libraries/ArduinoBearSSL/src/bearssl/i32_montmul.c"
                    "libraries/ArduinoBearSSL/src/bearssl/i32_mulacc.c"
                    "libraries/ArduinoBearSSL/src/bearssl/i32_muladd.c"
                    "libraries/ArduinoBearSSL/src/bearssl/i32_ninv32.c"
                    "libraries/ArduinoBearSSL/src/bearssl/i32_reduce.c"
                    "libraries/ArduinoBearSSL/src/bearssl/i32_sub.c"
                    "libraries/ArduinoBearSSL/src/bearssl/i32_tmont.c"
                    "libraries/ArduinoBearSSL/src/bearssl/i62_modpow2.c"
                    "libraries/ArduinoBearSSL/src/bearssl/LICENSE.txt"
                    "libraries/ArduinoBearSSL/src/bearssl/md5.c"
                    "libraries/ArduinoBearSSL/src/bearssl/md5sha1.c"
                    "libraries/ArduinoBearSSL/src/bearssl/mgf1.c"
                    "libraries/ArduinoBearSSL/src/bearssl/multihash.c"
                    "libraries/ArduinoBearSSL/src/bearssl/pemdec.c"
                    "libraries/ArduinoBearSSL/src/bearssl/pemenc.c"
                    "libraries/ArduinoBearSSL/src/bearssl/poly1305_ctmul32.c"
                    "libraries/ArduinoBearSSL/src/bearssl/poly1305_ctmul.c"
                    "libraries/ArduinoBearSSL/src/bearssl/poly1305_ctmulq.c"
                    "libraries/ArduinoBearSSL/src/bearssl/poly1305_i15.c"
                    "libraries/ArduinoBearSSL/src/bearssl/prf.c"
                    "libraries/ArduinoBearSSL/src/bearssl/prf_md5sha1.c"
                    "libraries/ArduinoBearSSL/src/bearssl/prf_sha256.c"
                    "libraries/ArduinoBearSSL/src/bearssl/prf_sha384.c"
                    "libraries/ArduinoBearSSL/src/bearssl/rsa_default_keygen.c"
                    "libraries/ArduinoBearSSL/src/bearssl/rsa_default_modulus.c"
                    "libraries/ArduinoBearSSL/src/bearssl/rsa_default_oaep_decrypt.c"
                    "libraries/ArduinoBearSSL/src/bearssl/rsa_default_oaep_encrypt.c"
                    "libraries/ArduinoBearSSL/src/bearssl/rsa_default_pkcs1_sign.c"
                    "libraries/ArduinoBearSSL/src/bearssl/rsa_default_pkcs1_vrfy.c"
                    "libraries/ArduinoBearSSL/src/bearssl/rsa_default_priv.c"
                    "libraries/ArduinoBearSSL/src/bearssl/rsa_default_privexp.c"
                    "libraries/ArduinoBearSSL/src/bearssl/rsa_default_pub.c"
                    "libraries/ArduinoBearSSL/src/bearssl/rsa_default_pubexp.c"
                    "libraries/ArduinoBearSSL/src/bearssl/rsa_i15_keygen.c"
                    "libraries/ArduinoBearSSL/src/bearssl/rsa_i15_modulus.c"
                    "libraries/ArduinoBearSSL/src/bearssl/rsa_i15_oaep_decrypt.c"
                    "libraries/ArduinoBearSSL/src/bearssl/rsa_i15_oaep_encrypt.c"
                    "libraries/ArduinoBearSSL/src/bearssl/rsa_i15_pkcs1_sign.c"
                    "libraries/ArduinoBearSSL/src/bearssl/rsa_i15_pkcs1_vrfy.c"
                    "libraries/ArduinoBearSSL/src/bearssl/rsa_i15_priv.c"
                    "libraries/ArduinoBearSSL/src/bearssl/rsa_i15_privexp.c"
                    "libraries/ArduinoBearSSL/src/bearssl/rsa_i15_pub.c"
                    "libraries/ArduinoBearSSL/src/bearssl/rsa_i15_pubexp.c"
                    "libraries/ArduinoBearSSL/src/bearssl/rsa_i31_keygen.c"
                    "libraries/ArduinoBearSSL/src/bearssl/rsa_i31_keygen_inner.c"
                    "libraries/ArduinoBearSSL/src/bearssl/rsa_i31_modulus.c"
                    "libraries/ArduinoBearSSL/src/bearssl/rsa_i31_oaep_decrypt.c"
                    "libraries/ArduinoBearSSL/src/bearssl/rsa_i31_oaep_encrypt.c"
                    "libraries/ArduinoBearSSL/src/bearssl/rsa_i31_pkcs1_sign.c"
                    "libraries/ArduinoBearSSL/src/bearssl/rsa_i31_pkcs1_vrfy.c"
                    "libraries/ArduinoBearSSL/src/bearssl/rsa_i31_priv.c"
                    "libraries/ArduinoBearSSL/src/bearssl/rsa_i31_privexp.c"
                    "libraries/ArduinoBearSSL/src/bearssl/rsa_i31_pub.c"
                    "libraries/ArduinoBearSSL/src/bearssl/rsa_i31_pubexp.c"
                    "libraries/ArduinoBearSSL/src/bearssl/rsa_i32_oaep_decrypt.c"
                    "libraries/ArduinoBearSSL/src/bearssl/rsa_i32_oaep_encrypt.c"
                    "libraries/ArduinoBearSSL/src/bearssl/rsa_i32_pkcs1_sign.c"
                    "libraries/ArduinoBearSSL/src/bearssl/rsa_i32_pkcs1_vrfy.c"
                    "libraries/ArduinoBearSSL/src/bearssl/rsa_i32_priv.c"
                    "libraries/ArduinoBearSSL/src/bearssl/rsa_i32_pub.c"
                    "libraries/ArduinoBearSSL/src/bearssl/rsa_i62_keygen.c"
                    "libraries/ArduinoBearSSL/src/bearssl/rsa_i62_oaep_decrypt.c"
                    "libraries/ArduinoBearSSL/src/bearssl/rsa_i62_oaep_encrypt.c"
                    "libraries/ArduinoBearSSL/src/bearssl/rsa_i62_pkcs1_sign.c"
                    "libraries/ArduinoBearSSL/src/bearssl/rsa_i62_pkcs1_vrfy.c"
                    "libraries/ArduinoBearSSL/src/bearssl/rsa_i62_priv.c"
                    "libraries/ArduinoBearSSL/src/bearssl/rsa_i62_pub.c"
                    "libraries/ArduinoBearSSL/src/bearssl/rsa_oaep_pad.c"
                    "libraries/ArduinoBearSSL/src/bearssl/rsa_oaep_unpad.c"
                    "libraries/ArduinoBearSSL/src/bearssl/rsa_pkcs1_sig_pad.c"
                    "libraries/ArduinoBearSSL/src/bearssl/rsa_pkcs1_sig_unpad.c"
                    "libraries/ArduinoBearSSL/src/bearssl/rsa_ssl_decrypt.c"
                    "libraries/ArduinoBearSSL/src/bearssl/settings.c"
                    "libraries/ArduinoBearSSL/src/bearssl/sha1.c"
                    "libraries/ArduinoBearSSL/src/bearssl/sha2big.c"
                    "libraries/ArduinoBearSSL/src/bearssl/sha2small.c"
                    "libraries/ArduinoBearSSL/src/bearssl/skey_decoder.c"
                    "libraries/ArduinoBearSSL/src/bearssl/ssl_ccert_single_ec.c"
                    "libraries/ArduinoBearSSL/src/bearssl/ssl_ccert_single_rsa.c"
                    "libraries/ArduinoBearSSL/src/bearssl/ssl_client.c"
                    "libraries/ArduinoBearSSL/src/bearssl/ssl_client_default_rsapub.c"
                    "libraries/ArduinoBearSSL/src/bearssl/ssl_client_full.c"
                    "libraries/ArduinoBearSSL/src/bearssl/ssl_engine.c"
                    "libraries/ArduinoBearSSL/src/bearssl/ssl_engine_default_aescbc.c"
                    "libraries/ArduinoBearSSL/src/bearssl/ssl_engine_default_aesccm.c"
                    "libraries/ArduinoBearSSL/src/bearssl/ssl_engine_default_aesgcm.c"
                    "libraries/ArduinoBearSSL/src/bearssl/ssl_engine_default_chapol.c"
                    "libraries/ArduinoBearSSL/src/bearssl/ssl_engine_default_descbc.c"
                    "libraries/ArduinoBearSSL/src/bearssl/ssl_engine_default_ec.c"
                    "libraries/ArduinoBearSSL/src/bearssl/ssl_engine_default_ecdsa.c"
                    "libraries/ArduinoBearSSL/src/bearssl/ssl_engine_default_rsavrfy.c"
                    "libraries/ArduinoBearSSL/src/bearssl/ssl_hashes.c"
                    "libraries/ArduinoBearSSL/src/bearssl/ssl_hs_client.c"
                    "libraries/ArduinoBearSSL/src/bearssl/ssl_hs_server.c"
                    "libraries/ArduinoBearSSL/src/bearssl/ssl_io.c"
                    "libraries/ArduinoBearSSL/src/bearssl/ssl_keyexport.c"
                    "libraries/ArduinoBearSSL/src/bearssl/ssl_lru.c"
                    "libraries/ArduinoBearSSL/src/bearssl/ssl_rec_cbc.c"
                    "libraries/ArduinoBearSSL/src/bearssl/ssl_rec_ccm.c"
                    "libraries/ArduinoBearSSL/src/bearssl/ssl_rec_chapol.c"
                    "libraries/ArduinoBearSSL/src/bearssl/ssl_rec_gcm.c"
                    "libraries/ArduinoBearSSL/src/bearssl/ssl_scert_single_ec.c"
                    "libraries/ArduinoBearSSL/src/bearssl/ssl_scert_single_rsa.c"
                    "libraries/ArduinoBearSSL/src/bearssl/ssl_server.c"
                    "libraries/ArduinoBearSSL/src/bearssl/ssl_server_full_ec.c"
                    "libraries/ArduinoBearSSL/src/bearssl/ssl_server_full_rsa.c"
                    "libraries/ArduinoBearSSL/src/bearssl/ssl_server_mine2c.c"
                    "libraries/ArduinoBearSSL/src/bearssl/ssl_server_mine2g.c"
                    "libraries/ArduinoBearSSL/src/bearssl/ssl_server_minf2c.c"
                    "libraries/ArduinoBearSSL/src/bearssl/ssl_server_minf2g.c"
                    "libraries/ArduinoBearSSL/src/bearssl/ssl_server_minr2g.c"
                    "libraries/ArduinoBearSSL/src/bearssl/ssl_server_minu2g.c"
                    "libraries/ArduinoBearSSL/src/bearssl/ssl_server_minv2g.c"
                    "libraries/ArduinoBearSSL/src/bearssl/sysrng.c"
                    "libraries/ArduinoBearSSL/src/bearssl/x509_decoder.c"
                    "libraries/ArduinoBearSSL/src/bearssl/x509_knownkey.c"
                    "libraries/ArduinoBearSSL/src/bearssl/x509_minimal.c"
                    "libraries/ArduinoBearSSL/src/bearssl/x509_minimal_full.c"

                    "libraries/ArduinoBearSSL/src/utility/eccX08_sign_asn1.cpp"
                    "libraries/ArduinoBearSSL/src/utility/eccX08_vrfy_asn1.cpp"

                    "libraries/ArduinoECCX08/src/ECCX08.cpp"

                    "libraries/ArduinoECCX08/src/utility/ASN1Utils.cpp"
                    "libraries/ArduinoECCX08/src/utility/ECCX08CSR.cpp"
                    "libraries/ArduinoECCX08/src/utility/ECCX08JWS.cpp"
                    "libraries/ArduinoECCX08/src/utility/ECCX08SelfSignedCert.cpp"
                    "libraries/ArduinoECCX08/src/utility/PEMUtils.cpp"
                    "libraries/ArduinoECCX08/src/utility/sha1.c"

                    "libraries/SPIS/src/SPIS.cpp"

                    "libraries/WiFi/src/WiFiClient.cpp"
                    "libraries/WiFi/src/WiFi.cpp"
                    "libraries/WiFi/src/WiFiServer.cpp"
                    "libraries/WiFi/src/WiFiSSLClient.cpp"
                    "libraries/WiFi/src/WiFiUdp.cpp"

                    "libraries/Wire/src/Wire.cpp"

    INCLUDE_DIRS    cores/esp32
                    libraries/SPIS/src
                    libraries/WiFi/src
                    libraries/Wire/src
                    libraries/ArduinoECCX08/src
                    libraries/ArduinoBearSSL/src

    REQUIRES        # esp_driver_gpio
                    nvs_flash
                    # esp_driver_ledc
                    driver
                    mbedtls
                    wpa_supplicant
    )
